/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mai_onsyn_renderer_cpu4dkt_JNIRasterizer */

#ifndef _Included_mai_onsyn_renderer_cpu4dkt_JNIRasterizer
#define _Included_mai_onsyn_renderer_cpu4dkt_JNIRasterizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mai_onsyn_renderer_cpu4dkt_JNIRasterizer
 * Method:    process
 * Signature: ([FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_mai_1onsyn_renderer_cpu4dkt_JNIRasterizer_process
  (JNIEnv *, jclass, jfloatArray, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
